# ===================================================================
# COMMON SPRING BOOT PROPERTIES
# ===================================================================

# ----------------------------------------
# CORE PROPERTIES
# ----------------------------------------

# ----------------------------------------
# WEB PROPERTIES
# ----------------------------------------

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 17010

version: v1.2.0.5
# Default language for the application
app:
  default:
    language: en-US

# Logging configuration
logging:
  level:
    # Logging level for Spring Framework web components
    org.springframework.web: debug
    # Logging level for custom application components
    com.fulinx.fulinx: debug
    # Logging level for external service components
    com.fulinx.fulinx.service.external: debug

# Spring Mail Configuration
spring:
  mail:
    host: smtp.zoho.com
    username: example@example.com
    password: example
    port: 465
    default-encoding: UTF-8
    protocol: smtps
    properties:
      mail:
        # Configuration for SSL encryption
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            # Enable SSL for secure connection
            enable: true
            required: true
          # Enable debug mode for troubleshooting
        debug: true

  # Redis Configuration for Caching and Data
  cache:
    type: redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
      lettuce:
        pool:
          # Maximum number of active connections in the pool
          max-active: 8
          # Maximum waiting time for a connection from the pool
          max-wait: -1
          # Maximum number of idle connections in the pool
          max-idle: 8
          # Minimum number of idle connections in the pool
          min-idle: 0

  # DataSource Configuration for connecting to MySQL Database
  datasource:
    url: >
      jdbc:mysql://localhost:3306/fulinx_spring_starter?useUnicode=true
      &characterEncoding=UTF-8
      &zeroDateTimeBehavior=convertToNull
      &autoReconnect=true
      &failOverReadOnly=false
      &useSSL=false
      &serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  # Security Configuration
  security:
    debug: true
    user:
      name: admin
      password: admin

  # Servlet Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# File-related Configuration
file:
  backup-dir:
    # General backup directory path
    general: 'backup/'
    # Backup directory path for Windows
    windows: 'd:/web/fulinx-springboot-starter/backup'
    # Backup directory path for Linux
    linux: '/usr/local/fulinx-springboot-starter/backup'
  upload-dir:
    # General upload directory path
    general: 'uploads/'
    # Upload directory path for Windows
    windows: 'd:/web/fulinx-springboot-starter/uploads/'
    # Upload directory path for Linux
    linux: '/usr/local/fulinx-springboot-starter/uploads/'
    # URL prefix for uploaded files
    urlPrefix: 'http://image.fulinx-springboot-starter.com/'

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.fulinx.spring.web.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh-CN

# Feign Client Configuration
feign:
  compression:
    request:
      # Enable compression for request
      enabled: true
      # Minimum request size to trigger compression
      min-request-size: 2048
      # Mime types to be compressed
      mime-types: text/xml,application/xml,application/json,text/javascript
    response:
      # Enable compression for response
      enabled: true
      # Use Gzip decoder for response
      useGzipDecoder: true
  okhttp:
    # Enable OkHttp client
    enabled: false
  client:
    default-to-properties: false
    config:
      default:
        # Logger level for default Feign client
        logger-level: FULL
        # Connection timeout for default Feign client
        connect-timeout: 60000
        # Read timeout for default Feign client
        read-timeout: 60000
        # Decode 404 response
        decode404: true
